import pandas as pd

disaster_data = [
    {
        "Year": 2015,
        "Location": "Chennai & Coastal TN, India",
        "Disaster_Name": "Catastrophic Chennai Urban Flood & Chembarambakkam Deluge",
        "Category": "Natural Coastal Flood",
        "Hazard_Type": "Extreme Inundation & Coastal Estuary Blocking",
        "Start_Date": "01-12-2015",
        "End_Date": "08-12-2015",
        "Duration_Days": 8,
        "Peak_Window": "Week 1 of December",
        "Moon_Phase_Regime": "Waning Gibbous (Syzygy Spring Tide Zone)",
        "Tidal_Influence": "Extreme Spring Tide Influence",
        "Exact_Moon_Detail": "Full Moon on 26 Nov 2015 | New Moon on 11 Dec 2015",
        "Casualty_Impact_Root_Cause": "Over 400mm rain in 24 hrs; Adyar river estuary blocked by elevated Bay of Bengal sea levels."
    },
    {
        "Year": 2015,
        "Location": "Gorkha & Kathmandu, Nepal",
        "Disaster_Name": "Nepal Gorkha Magnitude 7.8 Himalayan Earthquake",
        "Category": "Global Mega Earthquake",
        "Hazard_Type": "Major Continental Collision & Secondary Flash Deluges",
        "Start_Date": "25-04-2015",
        "End_Date": "28-04-2015",
        "Duration_Days": 4,
        "Peak_Window": "Week 4 of April",
        "Moon_Phase_Regime": "Waxing Crescent to First Quarter",
        "Tidal_Influence": "Neap Transition",
        "Exact_Moon_Detail": "First Quarter on 26 Apr 2015 | Full Moon on 04 May 2015",
        "Casualty_Impact_Root_Cause": "Destruction across Kathmandu valley and avalanche triggers across Mount Everest."
    },
    {
        "Year": 2016,
        "Location": "Chennai & Coastal TN, India",
        "Disaster_Name": "Very Severe Cyclonic Storm Vardah",
        "Category": "Natural Cyclonic Flood",
        "Hazard_Type": "Landfall Storm Surges & Wind Storm Inundation",
        "Start_Date": "12-12-2016",
        "End_Date": "14-12-2016",
        "Duration_Days": 3,
        "Peak_Window": "Week 2 of December",
        "Moon_Phase_Regime": "Full Moon Syzygy Alignment",
        "Tidal_Influence": "Peak Spring Tide Storm Surge",
        "Exact_Moon_Detail": "Full Moon (Supermoon) on 14 Dec 2016",
        "Casualty_Impact_Root_Cause": "130 km/h wind gusts coupled with high astronomical sea surge uprooted urban infrastructure."
    },
    {
        "Year": 2018,
        "Location": "Kerala, India",
        "Disaster_Name": "Kerala Great Monsoonal Inundation",
        "Category": "Natural Basin Flood",
        "Hazard_Type": "Dam Sluice Overflows, River Basin Deluges & Landslides",
        "Start_Date": "08-08-2018",
        "End_Date": "21-08-2018",
        "Duration_Days": 14,
        "Peak_Window": "Week 2 to Week 3 of August",
        "Moon_Phase_Regime": "New Moon (Amavasai - Direct Syzygy)",
        "Tidal_Influence": "Maximum Spring Tide (Arabian Sea Swell)",
        "Exact_Moon_Detail": "Exact New Moon (Amavasai) coincided on 11 Aug 2018",
        "Casualty_Impact_Root_Cause": "35 dams opened; massive tidal swell in Arabian Sea prevented Vembanad Lake and Periyar river discharge."
    },
    {
        "Year": 2021,
        "Location": "Uttarakhand & Nepal",
        "Disaster_Name": "Chamoli Glacial Lake Outburst Disaster (GLOF)",
        "Category": "Glacial Burst & Avalanche",
        "Hazard_Type": "Glacier Burst, Flash Deluge & Debris Avalanche",
        "Start_Date": "07-02-2021",
        "End_Date": "10-02-2021",
        "Duration_Days": 4,
        "Peak_Window": "Week 1 of February",
        "Moon_Phase_Regime": "Waning Crescent (Approaching Spring Tide)",
        "Tidal_Influence": "Gravitational Pre-Spring Phase",
        "Exact_Moon_Detail": "New Moon (Amavasai) was on 11 Feb 2021",
        "Casualty_Impact_Root_Cause": "Rishiganga dam crushed; high gravitational barometric swing recorded prior to glacial detachment."
    },
    {
        "Year": 2022,
        "Location": "Assam & Northeast, India",
        "Disaster_Name": "Assam-Silchar Historic Deluges",
        "Category": "Natural River Basin Flood",
        "Hazard_Type": "Brahmaputra & Barak River Basin Sinking",
        "Start_Date": "16-06-2022",
        "End_Date": "26-06-2022",
        "Duration_Days": 11,
        "Peak_Window": "Week 3 of June",
        "Moon_Phase_Regime": "Full Moon Syzygy Aftermath",
        "Tidal_Influence": "Peak Spring Tide Barrier",
        "Exact_Moon_Detail": "Full Moon (Supermoon) occurred on 14 Jun 2022",
        "Casualty_Impact_Root_Cause": "Bay of Bengal high astronomical tide pushed river discharge backward, drowning Silchar for 11 days."
    },
    {
        "Year": 2023,
        "Location": "Kahramanmaras, Turkey & Syria",
        "Disaster_Name": "Turkey-Syria Magnitude 7.8 Mega Dual Earthquake",
        "Category": "Global Mega Earthquake",
        "Hazard_Type": "Tectonic Plate Rupture & Mass Structural Collapse",
        "Start_Date": "06-02-2023",
        "End_Date": "12-02-2023",
        "Duration_Days": 7,
        "Peak_Window": "Week 1 of February",
        "Moon_Phase_Regime": "Full Moon (Exact Syzygy Alignment)",
        "Tidal_Influence": "Peak Gravitational Stress Alignment",
        "Exact_Moon_Detail": "Full Moon on 05 Feb 2023",
        "Casualty_Impact_Root_Cause": "East Anatolian Fault slip, 55,000+ casualties."
    },
    {
        "Year": 2023,
        "Location": "Himachal Pradesh & Delhi, India",
        "Disaster_Name": "Yamuna Historic Inundation & Beas Torrent",
        "Category": "Natural River Overflows",
        "Hazard_Type": "Cloudburst Floods & 45-Year Record High River Inundation",
        "Start_Date": "09-07-2023",
        "End_Date": "14-07-2023",
        "Duration_Days": 6,
        "Peak_Window": "Week 2 of July",
        "Moon_Phase_Regime": "Third Quarter (Half Moon Phase)",
        "Tidal_Influence": "Neap Tide Phase",
        "Exact_Moon_Detail": "Full Moon on 03 Jul 2023 | Third Quarter on 10 Jul 2023",
        "Casualty_Impact_Root_Cause": "Yamuna touched historic 208.66m submerging Red Fort corridors."
    },
    {
        "Year": 2023,
        "Location": "Chennai & Coastal TN, India",
        "Disaster_Name": "Cyclone Michaung Inundation",
        "Category": "Natural Coastal Flood",
        "Hazard_Type": "Intense Cyclonic Cloudburst & Coastal Swell",
        "Start_Date": "03-12-2023",
        "End_Date": "06-12-2023",
        "Duration_Days": 4,
        "Peak_Window": "Week 1 of December",
        "Moon_Phase_Regime": "Waning Gibbous (Active Spring Surge)",
        "Tidal_Influence": "Spring Tide Tidal Force",
        "Exact_Moon_Detail": "Full Moon on 27 Nov 2023 | New Moon on 12 Dec 2023",
        "Casualty_Impact_Root_Cause": "Bay of Bengal waves surged over 2.5 meters high, preventing storm drains from emptying."
    },
    {
        "Year": 2023,
        "Location": "Southern Tamil Nadu (Tirunelveli/Tuticorin)",
        "Disaster_Name": "Extreme Southern Tamil Nadu Deluge",
        "Category": "Natural Cloudburst Deluge",
        "Hazard_Type": "Atmospheric Vortex Cloudburst (950mm in Kayalpattinam)",
        "Start_Date": "17-12-2023",
        "End_Date": "19-12-2023",
        "Duration_Days": 3,
        "Peak_Window": "Week 3 of December",
        "Moon_Phase_Regime": "Waxing Crescent (Direct Spring Tide Window)",
        "Tidal_Influence": "Spring Tide Amplification",
        "Exact_Moon_Detail": "New Moon (Amavasai) on 12 Dec 2023",
        "Casualty_Impact_Root_Cause": "Gulf of Mannar sea water ingress coupled with record 950mm rain submerged Tuticorin railway lines."
    },
    {
        "Year": 2024,
        "Location": "Central & Coastal Japan",
        "Disaster_Name": "Noto Peninsula Magnitude 7.6 Earthquake & Tsunami",
        "Category": "Global Seismic & Tsunami Hazard",
        "Hazard_Type": "Shallow Crustal Rupture & Coastal Sea Surges",
        "Start_Date": "01-01-2024",
        "End_Date": "05-01-2024",
        "Duration_Days": 5,
        "Peak_Window": "Week 1 of January",
        "Moon_Phase_Regime": "Waning Gibbous to Third Quarter",
        "Tidal_Influence": "Neap Transition",
        "Exact_Moon_Detail": "Third Quarter on 04 Jan 2024 | New Moon on 11 Jan 2024",
        "Casualty_Impact_Root_Cause": "1.2m coastal tsunami waves and massive structural damage."
    },
    {
        "Year": 2024,
        "Location": "Dubai, United Arab Emirates (UAE)",
        "Disaster_Name": "Historic Gulf Super-Cell Cloudburst & Inundation",
        "Category": "Global Urban Deluge",
        "Hazard_Type": "Record Atmospheric Mesoscale Convective Vortex",
        "Start_Date": "16-04-2024",
        "End_Date": "18-04-2024",
        "Duration_Days": 3,
        "Peak_Window": "Week 3 of April",
        "Moon_Phase_Regime": "Waxing Gibbous",
        "Tidal_Influence": "Moderate Tidal Window",
        "Exact_Moon_Detail": "First Quarter on 15 Apr 2024 | Full Moon on 23 Apr 2024",
        "Casualty_Impact_Root_Cause": "Over 254mm rain in 24 hours paralyzed Dubai International Airport."
    },
    {
        "Year": 2024,
        "Location": "Chennai Industrial Corridor, Tamil Nadu",
        "Disaster_Name": "Kakkalur SIDCO Chemical & Paint Factory Explosion",
        "Category": "Industrial Chemical & Factory Fire",
        "Hazard_Type": "Industrial Chemical Blast & Toxic Vapor Flame",
        "Start_Date": "31-05-2024",
        "End_Date": "01-06-2024",
        "Duration_Days": 2,
        "Peak_Window": "Week 5 of May",
        "Moon_Phase_Regime": "Half Moon Phase",
        "Tidal_Influence": "Neap Tide (No Tidal Correlation)",
        "Exact_Moon_Detail": "Third Quarter (Half Moon) on 30 May 2024",
        "Casualty_Impact_Root_Cause": "Solvent drums detonated in SIDCO estate; summer heatwave aggravated chemical vapor pressure."
    },
    {
        "Year": 2024,
        "Location": "Chennai Industrial Belt, Tamil Nadu",
        "Disaster_Name": "Gummidipoondi SIPCOT Smelting Factory Boiler Explosion",
        "Category": "Industrial Chemical & Factory Fire",
        "Hazard_Type": "Heavy Industrial Boiler Blast & Structural Inferno",
        "Start_Date": "14-07-2024",
        "End_Date": "15-07-2024",
        "Duration_Days": 2,
        "Peak_Window": "Week 2 of July",
        "Moon_Phase_Regime": "First Quarter (Half Moon)",
        "Tidal_Influence": "Neap Tide",
        "Exact_Moon_Detail": "First Quarter (Half Moon) on 14 Jul 2024",
        "Casualty_Impact_Root_Cause": "High pressure boiler burst with flying shrapnel in industrial shift."
    },
    {
        "Year": 2024,
        "Location": "Wayanad, Kerala, India",
        "Disaster_Name": "Chooralmala-Mundakkai Mega Landslide Catastrophe",
        "Category": "Natural Landslide Deluge",
        "Hazard_Type": "Continuous Orographic Downpour & Multi-Debris Flow",
        "Start_Date": "30-07-2024",
        "End_Date": "03-08-2024",
        "Duration_Days": 5,
        "Peak_Window": "Week 5 of July",
        "Moon_Phase_Regime": "Waning Crescent (Pre-Amavasai Spring Build-up)",
        "Tidal_Influence": "Approaching Spring Tide",
        "Exact_Moon_Detail": "Full Moon on 21 Jul 2024 | New Moon on 04 Aug 2024",
        "Casualty_Impact_Root_Cause": "572mm rain in 48 hours collapsed mountain slopes, submerging settlements."
    },
    {
        "Year": 2024,
        "Location": "Kathmandu Valley, Nepal",
        "Disaster_Name": "Kathmandu Valley Monsoon Inundation",
        "Category": "Himalayan Flash Flood",
        "Hazard_Type": "Cloudburst & River Wall Overflows",
        "Start_Date": "27-09-2024",
        "End_Date": "29-09-2024",
        "Duration_Days": 3,
        "Peak_Window": "Week 4 of September",
        "Moon_Phase_Regime": "Waning Crescent (Syzygy Window)",
        "Tidal_Influence": "Spring Tide Alignment",
        "Exact_Moon_Detail": "Full Moon on 18 Sep 2024 | New Moon on 02 Oct 2024",
        "Casualty_Impact_Root_Cause": "Bagmati River breached all flood control retaining walls."
    },
    {
        "Year": 2025,
        "Location": "California, United States (USA)",
        "Disaster_Name": "Palisades & Eaton Mega Wildfire Disaster",
        "Category": "Global Wildfire Catastrophe",
        "Hazard_Type": "Santa Ana Wind-Driven Extreme Wildfire",
        "Start_Date": "07-01-2025",
        "End_Date": "16-01-2025",
        "Duration_Days": 10,
        "Peak_Window": "Week 2 of January",
        "Moon_Phase_Regime": "Full Moon (Syzygy Spring Tide)",
        "Tidal_Influence": "Extreme Atmospheric Tide Window",
        "Exact_Moon_Detail": "Full Moon on 13 Jan 2025",
        "Casualty_Impact_Root_Cause": "Over $160B in economic losses across Pacific belts."
    },
    {
        "Year": 2026,
        "Location": "Chennai North Industrial Zone, Tamil Nadu",
        "Disaster_Name": "Red Hills Vadakarai Chemical Warehouse Blaze",
        "Category": "Industrial Chemical & Factory Fire",
        "Hazard_Type": "Commercial Solvent Explosion & Toxic Vapor Fire",
        "Start_Date": "02-03-2026",
        "End_Date": "04-03-2026",
        "Duration_Days": 3,
        "Peak_Window": "Week 1 of March",
        "Moon_Phase_Regime": "Full Moon (Pournami)",
        "Tidal_Influence": "Spring Tide Alignment",
        "Exact_Moon_Detail": "Full Moon on 03 Mar 2026 (Exact Syzygy Peak)",
        "Casualty_Impact_Root_Cause": "Raw paint chemical drums exploded scattering debris across residential perimeters."
    },
    {
        "Year": 2026,
        "Location": "Brahmaputra Valley, Assam, India",
        "Disaster_Name": "Assam Pre-Monsoon Basin Submersion",
        "Category": "Natural River Basin Flood",
        "Hazard_Type": "River Embankment Breaches & Wetland Inundation",
        "Start_Date": "29-05-2026",
        "End_Date": "05-06-2026",
        "Duration_Days": 8,
        "Peak_Window": "Week 5 of May",
        "Moon_Phase_Regime": "Full Moon (Pournami)",
        "Tidal_Influence": "Spring Tide Alignment",
        "Exact_Moon_Detail": "Full Moon on 31 May 2026",
        "Casualty_Impact_Root_Cause": "Over 20 districts affected by swelling Brahmaputra tributaries with high tidal backpressure."
    },
    {
        "Year": 2026,
        "Location": "Manali Industrial Corridor, Chennai, Tamil Nadu",
        "Disaster_Name": "Manali Petrochemical Solvent Pipeline Flash Inferno",
        "Category": "Industrial Chemical & Factory Fire",
        "Hazard_Type": "Petrochemical Vaporization & Storage Tank Flare",
        "Start_Date": "08-06-2026",
        "End_Date": "10-06-2026",
        "Duration_Days": 3,
        "Peak_Window": "Week 2 of June",
        "Moon_Phase_Regime": "Half Moon Phase",
        "Tidal_Influence": "Neap Tide (Zero Ocean Surge Impact)",
        "Exact_Moon_Detail": "Third Quarter (Half Moon) on 07 Jun 2026",
        "Casualty_Impact_Root_Cause": "Summer heatwave above 41°C triggered volatile organic vapor pressure breach."
    },
    {
        "Year": 2026,
        "Location": "Wayanad & Idukki, Kerala, India",
        "Disaster_Name": "Kerala Southwest Monsoon Extreme Cloudburst Inundation",
        "Category": "Natural Landslide & Monsoon Deluge",
        "Hazard_Type": "Flash Flooding, Hill Slump & River Overflow",
        "Start_Date": "13-07-2026",
        "End_Date": "18-07-2026",
        "Duration_Days": 6,
        "Peak_Window": "Week 3 of July",
        "Moon_Phase_Regime": "New Moon (Amavasai)",
        "Tidal_Influence": "Peak Spring Tide (Arabian Sea Swell)",
        "Exact_Moon_Detail": "New Moon (Amavasai) on 14 Jul 2026",
        "Casualty_Impact_Root_Cause": "380mm downpours saturated Western Ghats hill ranges; Arabian Sea high tides delayed river discharge."
    }
]

df = pd.DataFrame(disaster_data)
csv_filename = "Global_Disaster_Database_2015_2026.csv"
df.to_csv(csv_filename, index=False, encoding='utf-8')
print(f"Success: '{csv_filename}' successfully created with {len(df)} historical entries!")